"""add tax rate to purchase orders

Revision ID: 7c380f8150d2
Revises: a5534953c3cf
Create Date: 2026-09-07 04:36:33.935211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c380f8150d2'
down_revision: Union[str, Sequence[str], None] = 'a5534953c3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "purchase_orders",
        sa.Column(
            "tax_rate",
            sa.Numeric(
                precision=8,
                scale=6,
            ),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE purchase_orders
        SET tax_rate = CASE
            WHEN currency IN ('USD', 'INR') THEN 0.18
            WHEN currency IN ('EUR', 'GBP') THEN 0.20
            ELSE NULL
        END
        """
    )

    op.alter_column(
        "purchase_orders",
        "tax_rate",
        existing_type=sa.Numeric(
            precision=8,
            scale=6,
        ),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'tax_rate')
    # ### end Alembic commands ###
